Repository wecode-bootcamp-korea/32-2nd-Daengcance-frontend, pull requests merged in 2022-05, with the labels that each got.

#5 [32기 이현정]Add: footer 레이아웃 구현 , map 기능 추가, 반응형 구현,리뷰 반영
  src/Components/Footer/Footer.js
  src/Components/Footer/footerData.js
  src/Router.js
Labels: Status: 리뷰 요청

#1 [ 32기 이수광 ] Nav 리뷰반영 완료 !
  public/images/DarkMode.png
  public/images/DarkMode2.png
  public/images/LOGO.png
  public/images/LOGO2.png
  public/images/LOGO3.png
  public/images/LOGO4.png
  public/images/btn.png
  public/images/btn2.png
  src/Components/Nav/Nav.js
  src/Router.js
Labels: Status: 리뷰 요청

#7 [32기 이현정]Modify: footer kakao login 경로 수정
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Router.js
  src/pages/Loginkakao/Loginkakao.js
Labels: Status: 리뷰 요청

#4 [32기 장형원] Add: Detail Page 기능구현 완료(최종완료)
  .vscode/extensions.json
  package-lock.json
  package.json
  public/index.html
  src/Components/Nav/Nav.js
  src/Router.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailAside/Asidecomponents/LocationMap.js
  src/pages/Detail/DetailAside/Asidecomponents/SitterLocation.js
  src/pages/Detail/DetailAside/Asidecomponents/UsageDate.js
  src/pages/Detail/DetailAside/Asidecomponents/UsageFee.js
  src/pages/Detail/DetailAside/DetailAside.js
  src/pages/Detail/DetailMain/DetailMain.js
  src/pages/Detail/DetailMain/DetailNormalSitter.js
  src/pages/Detail/DetailMain/DetailProSitter.js
  src/pages/Detail/DetailMain/DetailSitterInfo.js
  src/pages/Detail/DetailMain/DetailUsableService.js
  src/pages/Detail/DetailTopImg.js
Labels: Status: 수정 요청

#8 [32기 장형원] Fix: MyPage with MockData(최종 완료)
  src/Router.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyReservation.js
  src/pages/MyPage/MyReview.js
  src/pages/MyPage/PassedReservation.js
Labels: Status: 리뷰 요청

#10 [32기 장형원] Fix: 최종 확인(&&연산자 리뷰 반영)
  src/pages/Detail/DetailAside/Asidecomponents/UsageDate.js
Labels: Status: Accepted

#6 [32기 이현정]Add: Nav에 login & logout 구현 & nickname 구현
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Loginkakao/Loginkakao.js
  src/pages/Loginkakao/authData.js
Labels: Status: Accepted

#3 [32기 유동혁] Main UI 및 주소 API 구현 완료, 달력 구현 완료, 무한스크롤 완료, 다크모드 구현 완료
  package-lock.json
  package.json
  public/data/Main/petSitterData.json
  public/images/Main/arrowRight.svg
  public/images/Main/calendar.svg
  public/images/Main/search.svg
  public/images/Main/sort-solid.svg
  src/Components/Button/FilterButton.js
  src/Components/Button/SortButton.js
  src/Components/Loading/Loading.js
  src/Components/Nav/Nav.js
  src/Router.js
  src/pages/Main/DaumPostCode/DaumPostCode.js
  src/pages/Main/FilterWrapper/FilterWrapper.js
  src/pages/Main/Main.js
  src/pages/Main/MainCalendarModal/MainCalendarModal.js
  src/pages/Main/MainPostModal/MainPostModal.js
  src/pages/Main/PetSitterItem/PetSitterItem.js
  src/pages/Main/PetSitterList/PetSitterList.js
  src/pages/Main/PetSitterWrapper/PetSitterWrapper.js
Labels: Status: 리뷰 요청

#11 [32기 유동혁] Modify: 무한스크롤 loading할 때 흰색 배경 수정, Router관련 path 수정
  src/Router.js
  src/pages/Detail/Detail.js
  src/pages/Main/Main.js
  src/pages/Main/PetSitterList/PetSitterList.js
Labels: Status: 리뷰 요청
